### Exporing the raw data

In [3]:
import pandas as pd
import numpy as np
from pathlib import Path

# Current working directory for the notebook
dir = Path.cwd()

# Navigate to the root directory
root = dir.parent

# Define the absolute path of the file to be opened
data_dir = root / "data" / "raw"

# Read the files in loop and add the names for the files to the dataframes
dataframes = {}

for file_path in data_dir.glob("*.csv"):
    distinct_names = file_path.stem
    dataframes[distinct_names] = pd.read_csv(file_path)

print(dataframes.keys())

dict_keys(['olist_customers_dataset', 'olist_geolocation_dataset', 'olist_orders_dataset', 'olist_order_items_dataset', 'olist_order_payments_dataset', 'olist_order_reviews_dataset', 'olist_products_dataset', 'olist_sellers_dataset', 'product_category_name_translation'])

### Explore each dataframes

#### Customers file

In [4]:
customers = dataframes["olist_customers_dataset"]
customers.info()

print(f"Total duplicate rows = ",customers.duplicated().sum())
print("\nNull values in each columns")
customers.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB
Total duplicate rows =  0

Null values in each columns

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [5]:
customers.head(5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

#### Geolocation file

In [6]:
geolocation = dataframes["olist_geolocation_dataset"]
geolocation.info()
print(f"Total Duplicate rows = ", geolocation.duplicated().sum())
print("\nNull values in each columns")
geolocation.isna().sum()
print("Total Unique Zip codes = " ,geolocation['geolocation_zip_code_prefix'].nunique())

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB

Total Duplicate rows =  261831

Null values in each columns
Total Unique Zip codes =  19015

In [7]:
geolocation.head(5)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

#### Ordered Items

In [8]:
ordered_items = dataframes["olist_order_items_dataset"]
ordered_items.info()
print(f"Total Duplicate rows = ", ordered_items.duplicated().sum())
print("\nNull values in each columns")
ordered_items.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB
Total Duplicate rows =  0

Null values in each columns

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [9]:
ordered_items.head(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

#### Payments

In [10]:
payments = dataframes["olist_order_payments_dataset"]
payments.info()

print(f"Total Duplicate rows = ", payments.duplicated().sum())
print("\nNull Values in each columns")
payments.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB
Total Duplicate rows =  0

Null Values in each columns

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [11]:
payments.head(5)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

#### Order Reviews

In [12]:
reviews = dataframes["olist_order_reviews_dataset"]
reviews.info()
print(f"Total Duplicate rows = ", reviews.duplicated().sum())
print("\nNull Values in each columns")
reviews.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

Total Duplicate rows =  0

Null Values in each columns

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [13]:
reviews.head(5)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

#### Products

In [14]:
products = dataframes["olist_products_dataset"]
products.info()
print(f"Total Number of duplicate rows = ", products.duplicated().sum())
print("\nNull values in each columns")
products.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB
Total Number of duplicate rows =  0

Null values in each columns

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [15]:
products.head(5)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

#### Sellers

In [16]:
sellers = dataframes["olist_sellers_dataset"]
sellers.info()
print("Total Duplicate Rows = ", sellers.duplicated().sum())
print("\nNull values in each columns")
sellers.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB
Total Duplicate Rows =  0

Null values in each columns

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [17]:
sellers.head(5)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

#### Product category and its translations

In [18]:
product_category = dataframes["product_category_name_translation"]
product_category.info()
print("Total Duplicate rows = ", product_category.duplicated().sum() )
print("\nNull Values in each columns")
product_category.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB
Total Duplicate rows =  0

Null Values in each columns

product_category_name            0
product_category_name_english    0
dtype: int64

In [19]:
product_category.head(5)

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

#### Orders

In [20]:
orders = dataframes["olist_orders_dataset"]
orders.info()
print("Total Duplicate rows = ", orders.duplicated().sum() )
print("\nNull Values in each columns")
orders.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

Total Duplicate rows =  0

Null Values in each columns

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [21]:
orders.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

### Candidate Key test

In [33]:
def scan_candidate_keys(datasets_dict: dict[str, pd.DataFrame]) -> pd.DataFrame:
    results = []
    for datasets_name, df in datasets_dict.items():
        total_rows = len(df)
        for col in df.columns:
            unique_keys = df[col].nunique(dropna=False)
            duplicate_keys = total_rows - unique_keys
            is_unique = "Yes" if duplicate_keys == 0 else "No"

            results.append({
                "Dataset" : datasets_name,
                "Column Name" : col,
                "Total Rows" : total_rows,
                "Unique Keys" : unique_keys,
                "Duplicate Keys" : duplicate_keys,
                "Unique" : is_unique
            })
    return pd.DataFrame(results)

In [48]:
datasets = {"Customers" : customers,
            "Geolocation" : geolocation,
            "Ordered Items": ordered_items,
            "Payments" : payments,
            "Reviews" : reviews,
            "Orders" : orders,
            "Products" : products,
            "Sellers" : sellers,
            "Product category translation" : product_category}

report = scan_candidate_keys(datasets)
report[report["Dataset"] == "Customers"]

,Dataset,Column Name,Total Rows,Unique Keys,Duplicate Keys,Unique
0,Customers,customer_id,99441,99441,0,Yes
1,Customers,customer_unique_id,99441,96096,3345,No
2,Customers,customer_zip_code_prefix,99441,14994,84447,No
3,Customers,customer_city,99441,4119,95322,No
4,Customers,customer_state,99441,27,99414,No

In [49]:
report[report["Dataset"] == "Geolocation"]

,Dataset,Column Name,Total Rows,Unique Keys,Duplicate Keys,Unique
5,Geolocation,geolocation_zip_code_prefix,1000163,19015,981148,No
6,Geolocation,geolocation_lat,1000163,717360,282803,No
7,Geolocation,geolocation_lng,1000163,717613,282550,No
8,Geolocation,geolocation_city,1000163,8011,992152,No
9,Geolocation,geolocation_state,1000163,27,1000136,No

In [50]:
report[report["Dataset"] == "Ordered Items"]

,Dataset,Column Name,Total Rows,Unique Keys,Duplicate Keys,Unique
10,Ordered Items,order_id,112650,98666,13984,No
11,Ordered Items,order_item_id,112650,21,112629,No
12,Ordered Items,product_id,112650,32951,79699,No
13,Ordered Items,seller_id,112650,3095,109555,No
14,Ordered Items,shipping_limit_date,112650,93318,19332,No
15,Ordered Items,price,112650,5968,106682,No
16,Ordered Items,freight_value,112650,6999,105651,No

In [51]:
report[report["Dataset"] == "Payments"]

,Dataset,Column Name,Total Rows,Unique Keys,Duplicate Keys,Unique
17,Payments,order_id,103886,99440,4446,No
18,Payments,payment_sequential,103886,29,103857,No
19,Payments,payment_type,103886,5,103881,No
20,Payments,payment_installments,103886,24,103862,No
21,Payments,payment_value,103886,29077,74809,No

In [52]:
report[report["Dataset"] == "Reviews"]

,Dataset,Column Name,Total Rows,Unique Keys,Duplicate Keys,Unique
22,Reviews,review_id,99224,98410,814,No
23,Reviews,order_id,99224,98673,551,No
24,Reviews,review_score,99224,5,99219,No
25,Reviews,review_comment_title,99224,4528,94696,No
26,Reviews,review_comment_message,99224,36160,63064,No
27,Reviews,review_creation_date,99224,636,98588,No
28,Reviews,review_answer_timestamp,99224,98248,976,No

In [53]:
report[report["Dataset"] == "Orders"]

,Dataset,Column Name,Total Rows,Unique Keys,Duplicate Keys,Unique
29,Orders,order_id,99441,99441,0,Yes
30,Orders,customer_id,99441,99441,0,Yes
31,Orders,order_status,99441,8,99433,No
32,Orders,order_purchase_timestamp,99441,98875,566,No
33,Orders,order_approved_at,99441,90734,8707,No
34,Orders,order_delivered_carrier_date,99441,81019,18422,No
35,Orders,order_delivered_customer_date,99441,95665,3776,No
36,Orders,order_estimated_delivery_date,99441,459,98982,No

In [54]:
report[report["Dataset"] == "Products"]

,Dataset,Column Name,Total Rows,Unique Keys,Duplicate Keys,Unique
37,Products,product_id,32951,32951,0,Yes
38,Products,product_category_name,32951,74,32877,No
39,Products,product_name_lenght,32951,67,32884,No
40,Products,product_description_lenght,32951,2961,29990,No
41,Products,product_photos_qty,32951,20,32931,No
42,Products,product_weight_g,32951,2205,30746,No
43,Products,product_length_cm,32951,100,32851,No
44,Products,product_height_cm,32951,103,32848,No
45,Products,product_width_cm,32951,96,32855,No

In [56]:
report[report["Dataset"] == "Product category translation"]

,Dataset,Column Name,Total Rows,Unique Keys,Duplicate Keys,Unique
50,Product category translation,product_category_name,71,71,0,Yes
51,Product category translation,product_category_name_english,71,71,0,Yes

In [57]:
report[report["Dataset"] == "Sellers"]

,Dataset,Column Name,Total Rows,Unique Keys,Duplicate Keys,Unique
46,Sellers,seller_id,3095,3095,0,Yes
47,Sellers,seller_zip_code_prefix,3095,2246,849,No
48,Sellers,seller_city,3095,611,2484,No
49,Sellers,seller_state,3095,23,3072,No